FROM prod.registry.devshift.net/osio-prod/base/pcp:latest

RUN yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    yum install -y jq nc tar git && yum clean all

